{"name":"1e768a80-7778-4c66-89d6-46fd55e8a6fa","id":"/providers/Microsoft.Flow/flows/1e768a80-7778-4c66-89d6-46fd55e8a6fa","type":"Microsoft.Flow/flows","properties":{"apiId":"/providers/Microsoft.PowerApps/apis/shared_logicflows","displayName":"Pattern: Try-Catch-Finally","definition":{"metadata":{"workflowEntityId":null,"processAdvisorMetadata":null,"flowclientsuspensionreason":"None","flowclientsuspensiontime":null,"creator":{"id":"e1d4472e-0125-4313-9ba2-24667e75c696","type":"User","tenantId":"bbfde416-ad70-4316-81eb-73b70da0b6cd"},"provisioningMethod":"FromDefinition","failureAlertSubscription":true,"clientLastModifiedTime":"2021-05-01T10:18:43.1885667Z"},"$schema":"https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#","contentVersion":"1.0.0.0","parameters":{"$authentication":{"defaultValue":{},"type":"SecureObject"}},"triggers":{"manual":{"type":"Request","kind":"Button","inputs":{"schema":{"type":"object","properties":{},"required":[]}},"description":"Based on https://sharepains.com/2018/02/07/power-automate-try-catch-finally-flow/"}},"actions":{"Try":{"actions":{},"runAfter":{},"type":"Scope"},"Catch":{"actions":{},"runAfter":{"Try":["Failed"]},"type":"Scope"},"Finally":{"actions":{},"runAfter":{"Catch":["Succeeded","Skipped","Failed","TimedOut"]},"type":"Scope"}}},"connectionReferences":{},"flowFailureAlertSubscribed":false}}